### ISSUE TITLE
Remove Virtual Environment from Source.

### ISSUE THREAD

**Issue by chilusoft** [Nahidjc/loan-management-system-django#1]
***Remove the virtual environment from source***
It makes your repo unnecessarily big and it is not the recommended way. It is equivalent to pushing the node_modules folder.
Since you already have a ```requirements.txt``` file with a list of dependencies, exclude the env folder by adding its relative path, ```/env/*``` to the `.gitignore` file.  And also exclude your ```.pyc``` binaries. 

your .gitignore file, located at the root of your project, to the very least should have the following contents

***.gitignore***
```
*.pyc
*.sqlite3
*/__pycache__/*
/env/
```

**Comment by Nahidjc** [comment]
> _**Remove the virtual environment from source**_ It makes your repo unnecessarily big and it is not the recommended way. It is equivalent to pushing the node_modules folder. Since you already have a `requirements.txt` file with a list of dependencies, exclude the env folder by adding its relative path, `/env/*` to the `.gitignore` file. And also exclude your `.pyc` binaries.
> 
> your .gitignore file, located at the root of your project, to the very least should have the following contents
> 
> _**.gitignore**_
> 
> ```
> *.pyc
> *.sqlite3
> */__pycache__/*
> /env/
> ```

thank you
